/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Runtime-compiled HLSL source for the D3D11 fixed-function-emulation layer
// (RENDERER_PORT.md steps 5/6/7). D3D11Backend feeds these strings to D3DCompile
// at startup. They are a VERBATIM mirror of the human-readable, fxc-consumable
// Shaders/FFVertex.hlsl and Shaders/FFPixel.hlsl - keep all three in sync.
//
// - kFFVertexShaderHLSL: transform + fixed-function per-vertex lighting (step 7)
//   + forward the (lit-or-passthrough) diffuse and two texcoord sets + a
//   view-space fog coordinate.
// - kFFPixelShaderHLSL:  the texture-stage combiner ubershader (one shader
//   parameterized by cbCombiner, looping the active stages) followed by linear/
//   exp fog blending (step 7). The integer op/arg codes it uses mirror the
//   RenderBackendTexOp / RenderBackendTexArg enums in IRenderBackend.h.
//
// Matrix convention (documented in FFVertex.hlsl): WWMath Matrix4x4 is
// column-vector / OpenGL-style, uploaded row-by-row; the VS declares the matrices
// row_major and multiplies mul(matrix, vector).
//
// FIXED-FUNCTION LIGHTING EQUATION (step 7), evaluated per vertex when
// D3DRS_LIGHTING is enabled (LightingEnable != 0):
//
//   litColor.rgb = MatEmissive
//                + MatAmbient   * GlobalAmbient          (ambient term)
//                + sum over active directional lights of
//                      saturate(dot(N, -LightDir_i)) * MatDiffuse * LightDiffuse_i
//
// where MatDiffuse / MatAmbient resolve to either the material constant
// (D3DMCS_MATERIAL) or the interpolated vertex color (D3DMCS_COLOR1), selected by
// DiffuseSource / AmbientSource - mirroring D3DRS_*MATERIALSOURCE. N is the
// world-space normal. When lighting is disabled the vertex diffuse passes through
// unchanged (the pre-step-7 behavior), so every existing combiner/triangle assert
// is unaffected.

#pragma once

static const char kFFVertexShaderHLSL[] =
	"cbuffer cbPerObject : register(b0)\n"
	"{\n"
	"    row_major float4x4 WorldViewProj;\n"
	"};\n"
	"cbuffer cbLighting : register(b1)\n"
	"{\n"
	"    row_major float4x4 World;\n"
	"    row_major float4x4 View;\n"
	"    float4 GlobalAmbient;\n"
	"    float4 MatDiffuse;\n"
	"    float4 MatAmbient;\n"
	"    float4 MatEmissive;\n"
	"    float4 LightDir[4];\n"
	"    float4 LightDiffuse[4];\n"
	"    uint LightingEnable;\n"
	"    uint NumLights;\n"
	"    uint DiffuseSource;\n"
	"    uint AmbientSource;\n"
	"};\n"
	"#define MAX_BONES 64\n"
	"cbuffer cbSkinning : register(b2)\n"
	"{\n"
	"    row_major float4x4 Bones[MAX_BONES];\n"
	"    uint SkinningEnable;\n"
	"    uint3 _skinpad;\n"
	"    float4 Sway[11];\n"
	"    uint SwayEnable;\n"
	"    uint3 _swaypad;\n"
	"};\n"
	"cbuffer cbTexGen : register(b3)\n"
	"{\n"
	"    row_major float4x4 TexMat[4];\n"
	"    uint4 TexGen[4];\n"
	"};\n"
	"struct VSInput\n"
	"{\n"
	"    float3 pos     : POSITION;\n"
	"    float3 weights : BLENDWEIGHT;\n"
	"    uint4  indices : BLENDINDICES;\n"
	"    float3 normal  : NORMAL;\n"
	"    float4 color   : COLOR0;\n"
	"    float2 uv0     : TEXCOORD0;\n"
	"    float2 uv1     : TEXCOORD1;\n"
	"};\n"
	"struct VSOutput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"VSOutput main(VSInput input)\n"
	"{\n"
	"    VSOutput output;\n"
	"    float4 localPos    = float4(input.pos, 1.0);\n"
	"    float3 localNormal = input.normal;\n"
	"    if (SkinningEnable != 0u) {\n"
	"        float4 w;\n"
	"        w.x = input.weights.x;\n"
	"        w.y = input.weights.y;\n"
	"        w.z = input.weights.z;\n"
	"        w.w = 1.0 - (input.weights.x + input.weights.y + input.weights.z);\n"
	"        float3 blendedPos =\n"
	"            w.x * mul(Bones[input.indices.x], localPos).xyz +\n"
	"            w.y * mul(Bones[input.indices.y], localPos).xyz +\n"
	"            w.z * mul(Bones[input.indices.z], localPos).xyz +\n"
	"            w.w * mul(Bones[input.indices.w], localPos).xyz;\n"
	"        float3 blendedNormal =\n"
	"            w.x * mul((float3x3)Bones[input.indices.x], input.normal) +\n"
	"            w.y * mul((float3x3)Bones[input.indices.y], input.normal) +\n"
	"            w.z * mul((float3x3)Bones[input.indices.z], input.normal) +\n"
	"            w.w * mul((float3x3)Bones[input.indices.w], input.normal);\n"
	"        localPos    = float4(blendedPos, 1.0);\n"
	"        localNormal = blendedNormal;\n"
	"    }\n"
	"    if (SwayEnable != 0u) {\n"
	"        float h = localPos.z - input.normal.z;\n"
	"        localPos.xyz += h * Sway[(uint)input.normal.x].xyz;\n"
	"    }\n"
	"    output.pos = mul(WorldViewProj, localPos);\n"
	"    float4 diffuse = input.color;\n"
	"    if (LightingEnable != 0u) {\n"
	"        float3 N = normalize(mul((float3x3)World, localNormal));\n"
	"        float3 mDiff = (DiffuseSource == 1u) ? input.color.rgb : MatDiffuse.rgb;\n"
	"        float3 mAmb  = (AmbientSource == 1u) ? input.color.rgb : MatAmbient.rgb;\n"
	"        float3 col = MatEmissive.rgb + mAmb * GlobalAmbient.rgb;\n"
	"        [unroll] for (uint i = 0u; i < 4u; ++i) {\n"
	"            if (i < NumLights) {\n"
	"                float3 L = normalize(-LightDir[i].xyz);\n"
	"                float ndl = saturate(dot(N, L));\n"
	"                col += ndl * mDiff * LightDiffuse[i].rgb;\n"
	"            }\n"
	"        }\n"
	"        float a = (DiffuseSource == 1u) ? input.color.a : MatDiffuse.a;\n"
	"        diffuse = float4(saturate(col), a); // D3D8 clamps lit vertex colors before interpolation\n"
	"    }\n"
	"    output.color = diffuse;\n"
	"    output.uv0 = input.uv0;\n"
	"    output.uv1 = input.uv1;\n"
	"    float4 viewPos = mul(View, mul(World, localPos));\n"
	"    output.fog = viewPos.z;\n"
	"    float4 camPos = float4(viewPos.xyz, 1.0);\n"
	"    float2 g0 = float2(0.0, 0.0);\n"
	"    float2 g1 = float2(0.0, 0.0);\n"
	"    float2 g2 = float2(0.0, 0.0);\n"
	"    float2 g3 = float2(0.0, 0.0);\n"
	"    if (TexGen[0].x != 0u) g0 = (TexGen[0].y != 0u) ? mul(camPos, TexMat[0]).xy : camPos.xy;\n"
	"    if (TexGen[1].x != 0u) g1 = (TexGen[1].y != 0u) ? mul(camPos, TexMat[1]).xy : camPos.xy;\n"
	"    if (TexGen[2].x != 0u) g2 = (TexGen[2].y != 0u) ? mul(camPos, TexMat[2]).xy : camPos.xy;\n"
	"    if (TexGen[3].x != 0u) g3 = (TexGen[3].y != 0u) ? mul(camPos, TexMat[3]).xy : camPos.xy;\n"
	"    output.gen01 = float4(g0, g1);\n"
	"    output.gen23 = float4(g2, g3);\n"
	"    return output;\n"
	"}\n";

static const char kFFPixelShaderHLSL[] =
	"cbuffer cbCombiner : register(b0)\n"
	"{\n"
	"    uint gNumStages;\n"
	"    uint3 _pad0;\n"
	"    float4 gTFactor;\n"
	"    uint4 gStageColor[4];\n"
	"    uint4 gStageAlpha[4];\n"
	"    float4 gMonoLum;\n"
	"    float4 gMonoTint;\n"
	"    float4 gMonoFade;\n"
	"    uint gMonoEnable;\n"
	"    uint3 _padm;\n"
	"    uint gAlphaTestEnable;\n"
	"    uint gAlphaTestLE;\n"
	"    float gAlphaTestRef;\n"
	"    uint _padA;\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"cbuffer cbTexGen : register(b2)\n"
	"{\n"
	"    row_major float4x4 TexMat[4];\n"
	"    uint4 TexGen[4];\n"
	"};\n"
	"Texture2D gTex0 : register(t0);\n"
	"Texture2D gTex1 : register(t1);\n"
	"Texture2D gTex2 : register(t2);\n"
	"Texture2D gTex3 : register(t3);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"SamplerState gSmp2 : register(s2);\n"
	"SamplerState gSmp3 : register(s3);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"#define OP_DISABLE    0\n"
	"#define OP_SELECTARG1 1\n"
	"#define OP_SELECTARG2 2\n"
	"#define OP_MODULATE   3\n"
	"#define OP_MODULATE2X 4\n"
	"#define OP_ADD        5\n"
	"#define ARG_CURRENT 0\n"
	"#define ARG_DIFFUSE 1\n"
	"#define ARG_TEXTURE 2\n"
	"#define ARG_TFACTOR 3\n"
	"#define FOG_NONE   0\n"
	"#define FOG_LINEAR 1\n"
	"#define FOG_EXP    2\n"
	"#define FOG_EXP2   3\n"
	"float4 SampleStage(uint stage, float2 uv)\n"
	"{\n"
	"    switch (stage) {\n"
	"    case 0:  return gTex0.Sample(gSmp0, uv);\n"
	"    case 1:  return gTex1.Sample(gSmp1, uv);\n"
	"    case 2:  return gTex2.Sample(gSmp2, uv);\n"
	"    default: return gTex3.Sample(gSmp3, uv);\n"
	"    }\n"
	"}\n"
	"float3 ResolveColorArg(uint arg, float3 current, float3 texc, float3 diffuse)\n"
	"{\n"
	"    if (arg == ARG_TEXTURE) return texc;\n"
	"    if (arg == ARG_DIFFUSE) return diffuse;\n"
	"    if (arg == ARG_TFACTOR) return gTFactor.rgb;\n"
	"    return current;\n"
	"}\n"
	"float ResolveAlphaArg(uint arg, float current, float texa, float diffuse)\n"
	"{\n"
	"    if (arg == ARG_TEXTURE) return texa;\n"
	"    if (arg == ARG_DIFFUSE) return diffuse;\n"
	"    if (arg == ARG_TFACTOR) return gTFactor.a;\n"
	"    return current;\n"
	"}\n"
	"float3 ApplyColorOp(uint op, float3 a1, float3 a2, float3 current)\n"
	"{\n"
	"    if (op == OP_SELECTARG1) return a1;\n"
	"    if (op == OP_SELECTARG2) return a2;\n"
	"    if (op == OP_MODULATE)   return a1 * a2;\n"
	"    if (op == OP_MODULATE2X) return saturate(a1 * a2 * 2.0);\n"
	"    if (op == OP_ADD)        return saturate(a1 + a2);\n"
	"    return current;\n"
	"}\n"
	"float ApplyAlphaOp(uint op, float a1, float a2, float current)\n"
	"{\n"
	"    if (op == OP_SELECTARG1) return a1;\n"
	"    if (op == OP_SELECTARG2) return a2;\n"
	"    if (op == OP_MODULATE)   return a1 * a2;\n"
	"    if (op == OP_MODULATE2X) return saturate(a1 * a2 * 2.0);\n"
	"    if (op == OP_ADD)        return saturate(a1 + a2);\n"
	"    return current;\n"
	"}\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == FOG_EXP)  return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == FOG_EXP2) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"}\n"
	"float4 main(PSInput input) : SV_Target\n"
	"{\n"
	"    float3 curColor = input.color.rgb;\n"
	"    float  curAlpha = input.color.a;\n"
	"    float2 uvs[2] = { input.uv0, input.uv1 };\n"
	"    [unroll] for (uint s = 0; s < 4; ++s) {\n"
	"        if (s < gNumStages) {\n"
	"            uint tci = gStageColor[s].w & 1u;\n"
	"            float2 uv = uvs[tci];\n"
	"            if (TexGen[s].x != 0u) {\n"
	"                uv = (s == 0u) ? input.gen01.xy\n"
	"                   : (s == 1u) ? input.gen01.zw\n"
	"                   : (s == 2u) ? input.gen23.xy\n"
	"                   :             input.gen23.zw;\n"
	"            }\n"
	"            float4 tex = SampleStage(s, uv);\n"
	"            float3 c1 = ResolveColorArg(gStageColor[s].y, curColor, tex.rgb, input.color.rgb);\n"
	"            float3 c2 = ResolveColorArg(gStageColor[s].z, curColor, tex.rgb, input.color.rgb);\n"
	"            float3 newColor = ApplyColorOp(gStageColor[s].x, c1, c2, curColor);\n"
	"            float a1 = ResolveAlphaArg(gStageAlpha[s].y, curAlpha, tex.a, input.color.a);\n"
	"            float a2 = ResolveAlphaArg(gStageAlpha[s].z, curAlpha, tex.a, input.color.a);\n"
	"            float newAlpha = ApplyAlphaOp(gStageAlpha[s].x, a1, a2, curAlpha);\n"
	"            curColor = newColor;\n"
	"            curAlpha = newAlpha;\n"
	"        }\n"
	"    }\n"
	"    if (gMonoEnable != 0u) {\n"
	"        float g = dot(curColor, gMonoLum.rgb);\n"
	"        float4 tinted = g * gMonoTint;\n"
	"        float4 cur4 = lerp(float4(curColor, curAlpha), tinted, gMonoFade);\n"
	"        curColor = cur4.rgb;\n"
	"        curAlpha = cur4.a;\n"
	"    }\n"
	"    if (gAlphaTestEnable != 0u) {\n"
	"        if (gAlphaTestLE != 0u) {\n"
	"            if (curAlpha > gAlphaTestRef) discard;\n"
	"        } else {\n"
	"            if (curAlpha < gAlphaTestRef) discard;\n"
	"        }\n"
	"    }\n"
	"    if (FogEnable != 0u) {\n"
	"        float f = FogFactor(input.fog);\n"
	"        curColor = lerp(FogColor.rgb, curColor, f);\n"
	"    }\n"
	"    return float4(curColor, curAlpha);\n"
	"}\n";
